### PR TITLE
fix(frontend): default to use content order in table component

### PR DESCRIPTION
**Pull request by kauppie**
### Linked issue

Closes ducanhpham0312/zeevision-private#125

### Description

Table changed the order of the content by default. Now content is shown as is without sorting options applied.

Build on x64 Linux was also failing locally (not in a container), so I added the required dependencies to fix that.

### Testing

- Start test bench
- Start zeevision
- Initialize database

```sql
INSERT INTO processes(process_definition_key, bpmn_process_id, version, deployment_time)
VALUES(123, 'hello-world', 1, NOW());

INSERT INTO bpmn_resources(bpmn_process_id, bpmn_file)
VALUES('hello-world', '<the bpmn file>');

INSERT INTO instances(process_instance_key, process_definition_key, version, status, start_time)
VALUES(1, 123, 1, 'ACTIVE', NOW());
```

Wait a moment and add another instance (for the `start_time` to be different):

```sql
INSERT INTO instances(process_instance_key, process_definition_key, version, status, start_time)
VALUES(2, 123, 1, 'ACTIVE', NOW());
```

Validate that GraphQL and instance tables both have the instances in the same order, from newest to oldest.

### CODE REVIEW

**Comment by ducanhpham0312** [comment]
does it actually work now? and sorry for the test cases if they are a bit messy :)

**Comment by kauppie** [comment]
> does it actually work now? and sorry for the test cases if they are a bit messy :)

Seems to work. Although trying to test, use storybook or basically anything with `npm` fails locally starting from `34c42ac` with

```
Error: The package "@esbuild/linux-x64" could not be found, and is needed by esbuild.
```

**Review by ducanhpham0312 — COMMENTED** [review]
A couple issues when running `docker compose up --build`:
1. npm cannot install the needed dependencies
Screenshot 2023-11-23 at 23 11 52

2. zeevision failed to start
Screenshot 2023-11-23 at 23 13 05

**Comment by kauppie** [comment]
> A couple issues when running `docker compose up --build`:
> 
>     1. npm cannot install the needed dependencies
>        Screenshot 2023-11-23 at 23 11 52
> 
>     2. zeevision failed to start
>        Screenshot 2023-11-23 at 23 13 05

So I'll have to remove the @esbuild/linux-x64 dependency. Not sure what the solution then is.

You'll have to run `docker compose down --volumes` before starting zeevision. Likely cause of the failed migration is that there were some tables already defined.

**Review by ducanhpham0312 — APPROVED** [review]
LGTM

**Pull request merged**
